from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
from typing import Any
from xml.etree.ElementTree import Element, ElementTree, SubElement, indent

from .io import dump_json, iter_yaml, load_yaml
from .validate import require_valid_registry


def load_sources(root: Path) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    for path in iter_yaml(root, "sources"):
        data = load_yaml(path)
        if not isinstance(data, dict):
            continue
        item = deepcopy(data)
        item["registry_path"] = path.relative_to(root).as_posix()
        items.append(item)
    return sorted(items, key=lambda item: str(item["id"]))


def load_collections(root: Path) -> list[dict[str, Any]]:
    return [load_yaml(path) for path in iter_yaml(root, "collections")]


def load_profiles(root: Path) -> list[dict[str, Any]]:
    return [load_yaml(path) for path in iter_yaml(root, "profiles")]


def _primary_feed(source: dict[str, Any]) -> dict[str, Any]:
    return next(feed for feed in source["feeds"] if feed["role"] == "primary")


def _opml(title: str, sources: list[dict[str, Any]], output: Path) -> None:
    opml = Element("opml", {"version": "2.0"})
    head = SubElement(opml, "head")
    SubElement(head, "title").text = title
    body = SubElement(opml, "body")

    for source in sources:
        feed = _primary_feed(source)
        SubElement(
            body,
            "outline",
            {
                "type": "rss",
                "text": str(source["name"]),
                "title": str(source["name"]),
                "xmlUrl": str(feed["url"]),
                "htmlUrl": str(source["website"]),
                "techFeedsId": str(source["id"]),
            },
        )

    indent(opml, space="  ")
    output.parent.mkdir(parents=True, exist_ok=True)
    ElementTree(opml).write(output, encoding="utf-8", xml_declaration=True)


def _catalog(
    sources: list[dict[str, Any]], collections: list[dict[str, Any]], output: Path
) -> None:
    by_id = {source["id"]: source for source in sources}
    lines = [
        "# Awesome Tech Feeds Catalog",
        "",
        "Generated from the registry. Do not edit this file by hand.",
        "",
    ]
    for collection in sorted(collections, key=lambda item: str(item["id"])):
        lines.extend(
            [
                f"## {collection['name']}",
                "",
                str(collection["description"]),
                "",
            ]
        )
        for source_id in collection["sources"]:
            source = by_id[source_id]
            lines.append(
                f"- [{source['name']}]({source['website']}) — `{source['id']}`"
            )
        lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")


def compile_registry(root: Path, *, write: bool = True) -> dict[str, Any]:
    require_valid_registry(root)
    sources = load_sources(root)
    collections = sorted(load_collections(root), key=lambda item: str(item["id"]))
    profiles = sorted(load_profiles(root), key=lambda item: str(item["id"]))

    payload: dict[str, Any] = {
        "schema_version": 1,
        "counts": {
            "sources": len(sources),
            "collections": len(collections),
            "profiles": len(profiles),
        },
        "sources": sources,
        "collections": collections,
        "profiles": profiles,
    }

    if not write:
        return payload

    generated = root / "generated"
    generated.mkdir(parents=True, exist_ok=True)
    dump_json(generated / "registry.json", payload)

    compact_sources = []
    for source in sources:
        feed = _primary_feed(source)
        compact_sources.append(
            {
                "id": source["id"],
                "name": source["name"],
                "kind": source["kind"],
                "language": source["language"],
                "website": source["website"],
                "feed": feed["url"],
                "topics": source["topics"],
                "traits": source["traits"],
            }
        )
    dump_json(
        generated / "registry.min.json",
        {"schema_version": 1, "sources": compact_sources},
        compact=True,
    )

    active_sources = [source for source in sources if source["status"] == "active"]
    by_id = {source["id"]: source for source in active_sources}
    _opml("Awesome Tech Feeds — All", active_sources, generated / "all.opml")
    for collection in collections:
        selected = [by_id[source_id] for source_id in collection["sources"] if source_id in by_id]
        _opml(
            f"Awesome Tech Feeds — {collection['name']}",
            selected,
            generated / f"{collection['id']}.opml",
        )

    _catalog(sources, collections, generated / "catalog.md")
    return payload


def generated_files_match(root: Path) -> bool:
    generated = root / "generated"
    before = {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in generated.glob("*")
        if path.is_file() and path.name != "health.json"
    }
    compile_registry(root, write=True)
    after = {
        path.relative_to(root).as_posix(): path.read_bytes()
        for path in generated.glob("*")
        if path.is_file() and path.name != "health.json"
    }
    return before == after


def registry_as_json(root: Path) -> str:
    return json.dumps(compile_registry(root, write=False), ensure_ascii=False, indent=2) + "\n"
